name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install (API)
      working-directory: api
      run: |
        npm i || true
    - name: Install (WEB)
      working-directory: web
      run: |
        npm i || true
